<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260507181118 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Theme, RedFlag and BingoCard entities';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE bingo_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, cells JSON NOT NULL, marked_cells JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, theme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3999E97C59027487 ON bingo_card (theme_id)');
        $this->addSql('CREATE UNIQUE INDEX bingo_card_slug_unique ON bingo_card (slug)');
        $this->addSql('CREATE TABLE red_flag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, rarity VARCHAR(20) NOT NULL, theme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B4F0B1659027487 ON red_flag (theme_id)');
        $this->addSql('CREATE TABLE theme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, emoji VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX theme_slug_unique ON theme (slug)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE bingo_card ADD CONSTRAINT FK_3999E97C59027487 FOREIGN KEY (theme_id) REFERENCES theme (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE red_flag ADD CONSTRAINT FK_8B4F0B1659027487 FOREIGN KEY (theme_id) REFERENCES theme (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE bingo_card DROP CONSTRAINT FK_3999E97C59027487');
        $this->addSql('ALTER TABLE red_flag DROP CONSTRAINT FK_8B4F0B1659027487');
        $this->addSql('DROP TABLE bingo_card');
        $this->addSql('DROP TABLE red_flag');
        $this->addSql('DROP TABLE theme');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
